# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Projects/CGI/catAjax

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Projects/CGI/catAjax

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Projects/CGI/catAjax/CMakeFiles /home/pi/Projects/CGI/catAjax/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Projects/CGI/catAjax/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named catAjax

# Build rule for target.
catAjax: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 catAjax
.PHONY : catAjax

# fast build rule for target.
catAjax/fast:
	$(MAKE) -f CMakeFiles/catAjax.dir/build.make CMakeFiles/catAjax.dir/build
.PHONY : catAjax/fast

database.o: database.c.o

.PHONY : database.o

# target to build an object file
database.c.o:
	$(MAKE) -f CMakeFiles/catAjax.dir/build.make CMakeFiles/catAjax.dir/database.c.o
.PHONY : database.c.o

database.i: database.c.i

.PHONY : database.i

# target to preprocess a source file
database.c.i:
	$(MAKE) -f CMakeFiles/catAjax.dir/build.make CMakeFiles/catAjax.dir/database.c.i
.PHONY : database.c.i

database.s: database.c.s

.PHONY : database.s

# target to generate assembly for a file
database.c.s:
	$(MAKE) -f CMakeFiles/catAjax.dir/build.make CMakeFiles/catAjax.dir/database.c.s
.PHONY : database.c.s

logger.o: logger.c.o

.PHONY : logger.o

# target to build an object file
logger.c.o:
	$(MAKE) -f CMakeFiles/catAjax.dir/build.make CMakeFiles/catAjax.dir/logger.c.o
.PHONY : logger.c.o

logger.i: logger.c.i

.PHONY : logger.i

# target to preprocess a source file
logger.c.i:
	$(MAKE) -f CMakeFiles/catAjax.dir/build.make CMakeFiles/catAjax.dir/logger.c.i
.PHONY : logger.c.i

logger.s: logger.c.s

.PHONY : logger.s

# target to generate assembly for a file
logger.c.s:
	$(MAKE) -f CMakeFiles/catAjax.dir/build.make CMakeFiles/catAjax.dir/logger.c.s
.PHONY : logger.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/catAjax.dir/build.make CMakeFiles/catAjax.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/catAjax.dir/build.make CMakeFiles/catAjax.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/catAjax.dir/build.make CMakeFiles/catAjax.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... catAjax"
	@echo "... database.o"
	@echo "... database.i"
	@echo "... database.s"
	@echo "... logger.o"
	@echo "... logger.i"
	@echo "... logger.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

